import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('the app boots the native core and keeps playback mutations ordered', async () => {
  const [app, engine, store, payload, coreTypes, metadata, pages, player, desktopLyrics, remoteClients, neteaseLogin, localLibrary, widget, widgetPlugin, splash] = await Promise.all([
    readFile(new URL('../../App.tsx', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoAudioDspModule.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNativeAppStore.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNativeAppStorePayload.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNativeCoreTypes.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNativeMetadataService.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNativePagesView.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNativePlayerView.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNativeDesktopLyrics.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNativeRemoteClients.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNeteaseLoginView.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNativeLocalLibrary.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../targets/EchoWidget/EchoWidget.swift', import.meta.url), 'utf8'),
    readFile(new URL('../../plugins/withEchoWidget.js', import.meta.url), 'utf8'),
    readFile(new URL('../../modules/echo-audio-dsp/ios/EchoNativeSplashView.swift', import.meta.url), 'utf8'),
  ]);
  const nativeEntry = app.slice(app.indexOf('function NativeEchoApp'), app.indexOf('export default function App'));
  const appEntry = app.slice(app.indexOf('export default function App'));
  const tick = store.slice(store.indexOf('private func tickPlayback()'), store.indexOf('private func updateEstimatedRemotePosition'));
  const appBackgroundStart = player.indexOf('private var appBackground');
  const selectionStart = player.indexOf('private var selection');
  const themedTabStart = player.indexOf('private func themedTab');
  const titleStart = player.indexOf('private func title');
  const playerLayoutStart = player.indexOf('private func playerLayout');
  const lyricsLayoutStart = player.indexOf('private func lyricsLayout');
  const lyricsScrollerStart = player.indexOf('private func lyricsScroller');
  const lyricsHeader = player.slice(player.indexOf('private func lyricsHeader'), lyricsScrollerStart);
  const lyricAccessibilityStart = player.indexOf('private func lyricAccessibilityLabel');
  const artworkStart = player.indexOf('private func artwork');
  const statusHeader = player.slice(player.indexOf('private var statusHeader'), artworkStart);
  const progressControlStart = player.indexOf('private var progressControl');
  const trackDetails = player.slice(player.indexOf('private func trackDetails'), progressControlStart);
  const playbackModeSymbolStart = player.indexOf('private var playbackModeSymbol');
  const secondaryControls = player.slice(player.indexOf('private func secondaryControls'), playbackModeSymbolStart);
  const moreControls = player.slice(player.indexOf('private var moreControls'), player.indexOf('private var outputControl'));
  const streamingPlaylistStart = pages.indexOf('private func streamingPlaylistGridCard');
  const libraryPlaylistCard = pages.slice(pages.indexOf('private func libraryPlaylistCard'), streamingPlaylistStart);
  const libraryTrackRowStart = pages.indexOf('private func libraryTrackRow');
  const streamingPlaylistMenu = pages.slice(pages.indexOf('private func streamingPlaylistMenu'), libraryTrackRowStart);
  const pairingScannerStart = pages.indexOf('private struct EchoPairingScannerSheet');
  const playlistDetail = pages.slice(pages.indexOf('private struct EchoNativePlaylistDetailSheet'), pairingScannerStart);
  const collectionsStart = payload.indexOf('private func collectionsForCurrentView');
  const artistNamesStart = payload.indexOf('private func artistNames');
  const albumArtworkStart = store.indexOf('private func albumArtwork');
  const normalizedMetadataStart = store.indexOf('private func normalizedMetadataValue');
  const metadataRefreshStart = store.indexOf('private func refreshExternalMetadata');
  const artworkLookupStart = store.indexOf('func scheduleLibraryArtworkLookup');

  assert.ok(themedTabStart >= 0 && titleStart > themedTabStart);
  assert.ok(lyricsScrollerStart >= 0 && lyricAccessibilityStart > lyricsScrollerStart);
  assert.ok(collectionsStart >= 0 && artistNamesStart > collectionsStart);
  assert.ok(albumArtworkStart >= 0 && normalizedMetadataStart > albumArtworkStart);
  const themedTab = player.slice(themedTabStart, titleStart);
  const appBackground = player.slice(appBackgroundStart, selectionStart);
  const playerLayout = player.slice(playerLayoutStart, lyricsLayoutStart);
  const lyricsScroller = player.slice(lyricsScrollerStart, lyricAccessibilityStart);
  const collectionsForCurrentView = payload.slice(collectionsStart, artistNamesStart);
  const albumArtwork = store.slice(albumArtworkStart, normalizedMetadataStart);

  assert.match(nativeEntry, /<EchoNativeAppView/u);
  assert.doesNotMatch(nativeEntry, /migrationPayload === null/u);
  assert.match(appEntry, /<NativeEchoApp \/>/u);
  assert.doesNotMatch(appEntry, /<EchoLinkApp/u);
  assert.doesNotMatch(tick, /renderPages\(/u);
  assert.match(engine, /scheduleGeneration == generation/u);
  assert.match(engine, /playing && engine\.isRunning && player\.isPlaying/u);
  assert.match(store, /persistent\.playlists\[index\]\.tracks = queue/u);
  assert.match(store, /playbackLoadTask\?\.cancel\(\)/u);
  assert.match(store, /source == \.echo \|\| !powerampQueueManagedLocally/u);
  assert.match(store, /if currentTrack == nil \{[\s\S]*playerModel\.positionMs = 0/u);
  assert.match(store, /case "streamingQrResume": resumeNeteaseQrLogin\(\)/u);
  assert.match(coreTypes, /case \.normal: return \.repeatAll[\s\S]*case \.shuffle: return \.normal/u);
  assert.match(store, /case \.normal:\s+playAdjacent\(1, wraps: false\)/u);
  assert.match(store, /case \.repeatOne:[\s\S]*if automatic[\s\S]*case \.shuffle:/u);
  assert.match(store, /queue\.filter \{ trackKey\(\$0\) != currentKey \}/u);
  assert.match(store, /playerModel\.album = track\.album/u);
  assert.match(store, /let globalSearch = playerModel\.activePage == "search"/u);
  assert.match(store, /libraryQuery = ""[\s\S]*selectedStreamingPlaylistId = id/u);
  assert.match(store, /persistent\.recentTracks\.insert\(track, at: 0\)/u);
  assert.match(store, /persistent\.streamingQueueTracks = queue\.filter \{ \$0\.source == \.streaming \}/u);
  assert.match(store, /streamingSnapshots\[key\] \?\? track\(forKey: key\)/u);
  assert.match(store, /if mode != \.streaming \{ addRecent\(track\) \}/u);
  assert.match(store.slice(metadataRefreshStart, artworkLookupStart), /guard track\.source != \.streaming else \{ return \}/u);
  assert.match(store, /track\.source == \.streaming \{ lyrics = \(try\? await neteaseClient\?\.lyrics/u);
  assert.match(store, /neteaseClient\.trackDetail\(trackId: track\.id\)/u);
  assert.match(store.slice(artworkLookupStart, store.indexOf('private func resetLibraryArtworkLookup')), /guard track\.source != \.streaming else \{ return false \}/u);
  assert.match(store, /streamingSearchStatus = errorMessage\(error\)/u);
  assert.match(store, /value\.hasPrefix\("MUSIC_U="\)/u);
  assert.match(payload, /let showingCollections = selectedTracks == nil/u);
  assert.match(payload, /if libraryCollectionsCacheKey == cacheKey \{[\s\S]*return libraryCollectionsCache/u);
  assert.match(payload, /if cacheable, libraryTracksCacheKey == cacheKey \{ return libraryTracksCache \}/u);
  assert.match(payload, /collectionTrackKeys\[id\]\?\.lazy\.compactMap\(track\(forKey:\)\)\.first/u);
  assert.match(payload, /if source == "echo", libraryView == "albums"/u);
  assert.match(payload, /let id = "echo:album-id:\\\(album\.id\)"/u);
  assert.match(payload, /option\("history", localized\("History", "历史"\)\)/u);
  assert.match(payload, /case "default": return tracks/u);
  assert.match(payload, /case "artist": return sortedByText\(\\\.artist, tie: \\\.title\)/u);
  assert.match(payload, /case "duration": return tracks\.sorted/u);
  assert.match(payload, /private func sortLibraryCollections\(_ collections: \[\[String: Any\]\]\)/u);
  assert.match(payload, /guard librarySort != "default" else \{ return collections \}/u);
  assert.match(payload, /return collections\.sorted \{ left, right in/u);
  assert.match(payload, /case "artist":[\s\S]*"sortArtist"[\s\S]*case "duration":[\s\S]*"sortDuration"/u);
  assert.match(payload, /collections\.map \{ \$0\["indexTitle"\]/u);
  assert.match(payload, /\(65\.\.\.90\)\.contains/u);
  assert.match(collectionsForCurrentView, /let key = normalized\(title\)/u);
  assert.match(collectionsForCurrentView, /formUnion\(trackArtistComparisonValues\(track\.artist\)\)/u);
  assert.doesNotMatch(collectionsForCurrentView, /albumArtist/u);
  assert.match(payload, /return Double\(matches\) \/ Double\(longestCount\)/u);
  assert.doesNotMatch(albumArtwork, /albumArtist/u);
  assert.match(coreTypes, /recentTracks = try values\.decodeIfPresent\(\[EchoNativeCoreTrack\]\.self, forKey: \.recentTracks\) \?\? \[\]/u);
  assert.match(coreTypes, /streamingQueueTracks = try values\.decodeIfPresent\(\[EchoNativeCoreTrack\]\.self, forKey: \.streamingQueueTracks\) \?\? \[\]/u);
  assert.match(coreTypes, /var desktopLyricsEnabled = false/u);
  assert.match(coreTypes, /desktopLyricsEnabled = try values\.decodeIfPresent\(Bool\.self, forKey: \.desktopLyricsEnabled\) \?\? false/u);
  assert.match(metadata, /guard !text\.isEmpty else \{ continue \}/u);
  assert.match(metadata, /Dictionary\(grouping: result\) \{ Int\(\$0\.milliseconds\.rounded\(\)\) \}/u);
  assert.match(metadata, /seen\.insert\(\$0\.text\)\.inserted/u);
  assert.match(metadata, /\.joined\(separator: "\\n"\)/u);
  assert.match(metadata, /let tlyric: Value\?/u);
  assert.match(player, /case \.normal: return "arrow\.right\.to\.line"/u);
  assert.match(playerLayout, /let coverMaximum: CGFloat = compact \? 200 : 310/u);
  assert.match(playerLayout, /outputControl/u);
  assert.match(player, /private var moreControls: some View \{\s+Menu \{/u);
  assert.match(secondaryControls, /HStack\(spacing: 0\)/u);
  assert.equal((secondaryControls.match(/\.frame\(maxWidth: \.infinity\)/gu) ?? []).length, 5);
  assert.doesNotMatch(player, /queueCount/u);
  assert.doesNotMatch(store, /queueCount/u);
  assert.match(player, /showPlayerOutputInMenu/u);
  assert.match(payload, /toggle\("playerOutputInMenu"/u);
  assert.match(coreTypes, /var showPlayerOutputInMenu = true/u);
  assert.match(coreTypes, /showPlayerOutputInMenu = try values\.decodeIfPresent\(Bool\.self, forKey: \.showPlayerOutputInMenu\) \?\? true/u);
  assert.match(player, /Label\(model\.language == "en" \? "Signal path" : "信号路径"/u);
  assert.match(player, /EchoNativeSignalPathSheet\(model: model, onAction: onAction\)[\s\S]*?\.echoMediumSheet\(\)/u);
  assert.match(player, /struct EchoNativeSignalPathSheet/u);
  assert.match(store, /private func updateSignalPath\(for track: EchoNativeCoreTrack\)/u);
  assert.match(player, /"Signal theater" : "信号剧场"/u);
  assert.match(player, /"Full chain" : "完整链路"/u);
  assert.match(player, /"Signal doctor" : "信号医生"/u);
  assert.match(player, /"Route flight recorder" : "路径飞行记录器"/u);
  assert.match(player, /struct EchoNativeSignalRouteEvent: Codable/u);
  assert.match(player, /struct EchoNativeDacObservation: Codable/u);
  assert.match(player, /struct EchoNativeSignalLiveMeter: View/u);
  assert.match(player, /"DAC capability atlas" : "DAC 能力图谱"/u);
  assert.match(player, /"Observed" : "已观测"/u);
  assert.match(player, /"Remote reported" : "远程上报"/u);
  assert.match(player, /default: return "\?"/u);
  assert.match(store, /recordSignalRouteObservation\(for track:/u);
  assert.match(store, /recordDacObservation\(_ status: DspPlaybackStatus\)/u);
  assert.match(store, /case "signalPathVisible"/u);
  assert.match(player, /"action": "signalPathVisible"/u);
  assert.match(player, /struct EchoNativeSignalIconAnchorKey: PreferenceKey/u);
  assert.match(player, /backgroundPreferenceValue\(EchoNativeSignalIconAnchorKey\.self\)/u);
  assert.match(player, /anchorPreference\(key: EchoNativeSignalIconAnchorKey\.self/u);
  assert.doesNotMatch(player, /private func signalConnector/u);
  assert.match(player, /TimelineView\(\.animation\(minimumInterval: 1\.0 \/ 30\.0, paused: reduceMotion\)\)/u);
  assert.match(player, /if model\.signalFileLoaded \{ return "AVAudioFile → PCM" \}/u);
  assert.doesNotMatch(player, /AVAudioFile → PCM ·/u);
  assert.match(player, /case nil: return english \? "Resampling: \?" : "重采样：\?"/u);
  assert.match(player, /Resampling: active/u);
  assert.match(coreTypes, /struct AudioTelemetry: Decodable, Sendable/u);
  assert.match(engine, /let channelCount: Int/u);
  assert.match(engine, /let deviceSampleRate: Double/u);
  assert.match(engine, /session\.currentRoute\.outputs\.first/u);
  assert.match(engine, /installTap\(onBus: 0/u);
  assert.match(engine, /let peakDb: Double/u);
  assert.match(engine, /let sampleRate: Double/u);
  assert.match(store, /playerModel\.eqEnabled = /u);
  assert.match(player, /private var showsConnectionStatus: Bool \{\s+outputSource == "echo" \|\| outputSource == "remote"/u);
  assert.match(player, /@Published var outputMode = "local"/u);
  assert.match(player, /model\.tags\.joined\(separator:/u);
  assert.match(player, /private var outputControl: some View/u);
  assert.match(player, /GeometryReader \{ geometry in[\s\S]*outputSourcePicker[\s\S]*outputModePicker/u);
  assert.equal((player.match(/"action": "trackFavoriteCurrent"/gu) ?? []).length, 1);
  assert.doesNotMatch(player, /Label\(model\.language == "en" \? "Playback output" : "播放输出", systemImage: "airplayaudio"\)/u);
  assert.match(player, /Text\(albumLabel\)/u);
  assert.doesNotMatch(player, /Text\(model\.language == "en" \? "NOW PLAYING" : "正在播放"\)/u);
  assert.match(lyricsHeader, /let artworkSize: CGFloat = compact \? 76 : 96/u);
  assert.ok(lyricsHeader.indexOf('Text(albumLabel)') < lyricsHeader.indexOf('Text(artistLabel)'));
  assert.match(lyricsHeader, /Image\(systemName: "rectangle\.stack\.fill"\)/u);
  assert.match(lyricsHeader, /Image\(systemName: "person\.fill"\)/u);
  assert.match(lyricsHeader, /Image\(systemName: "waveform"\)/u);
  assert.match(lyricsHeader, /model\.tags\.joined\(separator: "  ·  "\)/u);
  assert.doesNotMatch(lyricsHeader, /Capsule/u);
  assert.match(statusHeader, /Image\(systemName: "rectangle\.stack\.fill"\)/u);
  assert.match(trackDetails, /Image\(systemName: "person\.fill"\)/u);
  assert.match(trackDetails, /Image\(systemName: "waveform"\)/u);
  assert.match(player, /\.blur\(radius: 14, opaque: true\)/u);
  assert.match(player, /No song is playing/u);
  assert.match(player, /hostingController\.overrideUserInterfaceStyle = style/u);
  assert.match(player, /backgroundColor = UIColor \{ traits in/u);
  assert.match(player, /hostingController\.view\.isOpaque = false/u);
  assert.match(player, /@Published var lyricLines:/u);
  assert.match(player, /ForEach\(Array\(model\.lyricLines\.enumerated\(\)\), id: \\.offset\)/u);
  assert.doesNotMatch(player, /EchoNativeDesktopLyricsOverlay/u);
  assert.match(desktopLyrics, /AVPictureInPictureController/u);
  assert.match(desktopLyrics, /AVSampleBufferDisplayLayer/u);
  assert.match(desktopLyrics, /CVPixelBufferCreate/u);
  assert.match(desktopLyrics, /didTransitionToRenderSize/u);
  assert.match(desktopLyrics, /CMTimebaseCreateWithSourceClock/u);
  assert.match(desktopLyrics, /isPictureInPicturePossible/u);
  assert.match(desktopLyrics, /presentationTimeStamp: CMClockGetTime/u);
  assert.match(desktopLyrics, /kCVPixelBufferIOSurfacePropertiesKey/u);
  assert.match(desktopLyrics, /kCMSampleAttachmentKey_DisplayImmediately/u);
  assert.match(desktopLyrics, /activateAudioSession\(\)/u);
  assert.match(desktopLyrics, /canvasWidth\(for: configuration\.widthScale\)/u);
  assert.match(desktopLyrics, /canvasHeight\(for: configuration\.heightScale\)/u);
  assert.match(desktopLyrics, /CIFilter\.gaussianBlur\(\)/u);
  assert.match(desktopLyrics, /startRenderTimer\(interval: needsContinuousRendering \? 1\.0 \/ 30\.0 : 0\.5\)/u);
  assert.match(desktopLyrics, /Timer\(timeInterval: interval/u);
  assert.match(desktopLyrics, /RunLoop\.main\.add\(timer, forMode: \.common\)/u);
  assert.match(desktopLyrics, /renderTimerInterval \* 2/u);
  assert.match(desktopLyrics, /configuration\.visualizer != "off"/u);
  assert.doesNotMatch(desktopLyrics, /withTimeInterval: 0\.5/u);
  assert.match(desktopLyrics, /preferredTimescale: 600/u);
  assert.match(desktopLyrics, /previousLyric = currentLyric/u);
  assert.match(desktopLyrics, /drawCover\(in: cover/u);
  assert.match(desktopLyrics, /artworkBackgroundImage/u);
  assert.match(desktopLyrics, /positionUpdatedAt/u);
  assert.match(desktopLyrics, /private var hasRenderedFrame = false/u);
  assert.match(desktopLyrics, /guard displayLayer\.isReadyForMoreMediaData, let sampleBuffer = makeSampleBuffer\(\) else \{ return \}/u);
  assert.match(desktopLyrics, /hasRenderedFrame,[\s\S]*pictureInPictureController\.isPictureInPicturePossible/u);
  assert.doesNotMatch(desktopLyrics, /renderScale/u);
  assert.match(desktopLyrics, /paragraph\.alignment = \.left/u);
  assert.match(desktopLyrics, /let lines = text\.components\(separatedBy: \.newlines\)/u);
  assert.match(desktopLyrics, /lineWidth \* CGFloat\(progress\)/u);
  assert.match(desktopLyrics, /private func lyricScrollOffset/u);
  assert.match(desktopLyrics, /lineWidth \* CGFloat\(progress\) - viewportWidth \* 0\.78/u);
  assert.match(desktopLyrics, /private func drawRainbowText/u);
  assert.match(desktopLyrics, /context\.beginTransparencyLayer/u);
  assert.match(desktopLyrics, /context\.setBlendMode\(\.sourceIn\)/u);
  assert.doesNotMatch(desktopLyrics, /for character in text/u);
  assert.match(desktopLyrics, /saturation: 0\.38/u);
  assert.match(desktopLyrics, /restoreRequested = true/u);
  assert.match(desktopLyrics, /if !hasTrack \{[\s\S]*hasRenderedFrame = false[\s\S]*renderFrame\(\)/u);
  assert.match(desktopLyrics, /context\.setFillColor\(base\.cgColor\)/u);
  assert.match(desktopLyrics, /self\.trackKey != trackKey/u);
  assert.match(desktopLyrics, /max\(8, inset - 8\)/u);
  assert.ok(desktopLyrics.indexOf('drawBackground(in: context') < desktopLyrics.indexOf('drawVisualizer(in: context'));
  assert.ok(desktopLyrics.indexOf('drawVisualizer(in: context') < desktopLyrics.indexOf('drawCover(in: cover'));
  assert.match(desktopLyrics, /case "wave":/u);
  assert.match(desktopLyrics, /case "pulse":/u);
  assert.match(desktopLyrics, /private var visualizationLevel/u);
  assert.match(desktopLyrics, /private static let artworkCache/u);
  assert.match(desktopLyrics, /没有歌曲正在播放/u);
  assert.match(desktopLyrics, /themeColorHex/u);
  assert.match(player, /private var appBackground: some View/u);
  assert.match(payload, /Software default/u);
  assert.match(payload, /Default light gold/u);
  assert.match(payload, /Night purple/u);
  assert.match(store, /addRecent\(updated\)/u);
  assert.match(store, /lyrics = track\.externalLyrics \?\? ""/u);
  assert.match(store, /value\.artworkUrl = cached\.artworkUrl/u);
  assert.match(coreTypes, /var externalArtworkUrl: String\?/u);
  assert.doesNotMatch(store, /failedArtworkUrls/u);
  assert.doesNotMatch(store, /externalLyricsByTrackKey/u);
  assert.match(store, /scheduleExternalMetadataRetry\(for: currentTrack\)/u);
  assert.match(store, /if candidates\.isEmpty \{\s+scheduleExternalMetadataRetry\(for: track\)/u);
  assert.match(store, /let delays: \[UInt64\] = \[2, 8, 30\]/u);
  assert.match(store, /neteaseClient: metadataNeteaseClient/u);
  assert.match(store, /scheduleLocalMetadataEmbedding\(updated\)/u);
  assert.match(store, /scannedTracks\.map \{ resolvedTrack\(\$0, includeLibraryFallback: false\) \}/u);
  assert.match(store, /values\.1\.map \{ resolvedTrack\(\$0, includeLibraryFallback: false\) \}/u);
  assert.match(metadata, /configuration\.waitsForConnectivity = true/u);
  assert.match(metadata, /client\.search\("\\\(track\.title\) \\\(track\.artist\)", limit: 8\)/u);
  assert.doesNotMatch(store.slice(artworkLookupStart, store.indexOf('private func resetLibraryArtworkLookup')), /externalMetadataSkipExisting/u);
  assert.match(metadata, /cacheLyrics\(_ lyrics: String/u);
  assert.match(metadata, /static func text\(from url: URL\) async/u);
  assert.match(remoteClients, /private func responseData\(for request: URLRequest\)/u);
  assert.match(localLibrary, /static func embedExternalMetadata/u);
  assert.match(localLibrary, /appendingPathExtension\("echo-metadata\.json"\)/u);
  assert.match(coreTypes, /var desktopLyricsFontSize = 32\.0/u);
  assert.match(coreTypes, /var desktopLyricsBackground = "artwork"/u);
  assert.match(coreTypes, /var desktopLyricsTimedReveal = true/u);
  assert.match(coreTypes, /var desktopLyricsTransitionAnimation = true/u);
  assert.match(coreTypes, /var desktopLyricsRainbowGradient = false/u);
  assert.match(coreTypes, /var desktopLyricsVisualizer = "off"/u);
  assert.match(coreTypes, /var showPowerampRemote = true/u);
  assert.match(coreTypes, /var themeColorHex = "69508F"/u);
  assert.match(app, /showPowerampRemote: settings\.showPowerampRemoteConnection \?\? true/u);
  assert.match(payload, /desktopLyricsSize"[\s\S]*min: 18, max: 48/u);
  assert.match(payload, /toggle\("desktopLyricsRainbowGradient"/u);
  assert.match(payload, /picker\("desktopLyricsVisualizer"/u);
  assert.doesNotMatch(desktopLyrics, /NSShadow|panelColor|motionOffset/u);
  assert.match(metadata, /\.joined\(separator: "\\n"\)/u);
  assert.match(store, /attachDesktopLyrics\(to view: UIView\)/u);
  assert.match(store, /desktopLyricsController\.configure/u);
  assert.match(store, /desktopLyricsController\.update/u);
  assert.match(player, /store\.attachDesktopLyrics\(to: self\)/u);
  assert.match(player, /Toggle\(isOn: Binding\([\s\S]*desktopLyricsEnabled/u);
  assert.match(payload, /slider\("desktopLyricsSize"/u);
  assert.match(payload, /slider\("desktopLyricsWidth"/u);
  assert.match(payload, /desktopLyricsWidth"[\s\S]*min: 0\.2, max: 1\.0/u);
  assert.match(payload, /slider\("desktopLyricsHeight"/u);
  assert.match(payload, /picker\("desktopLyricsBackground"/u);
  assert.match(payload, /action\("desktopLyricsImportBackground"/u);
  assert.match(payload, /toggle\("desktopLyricsTransitionAnimation"/u);
  assert.match(payload, /toggle\("desktopLyricsTimedReveal"/u);
  assert.doesNotMatch(payload, /desktopLyricsStyle/u);
  assert.match(payload, /Fill every lyric line smoothly from left to right in white/u);
  assert.doesNotMatch(payload, /slider\("desktopLyricsOpacity"/u);
  assert.match(pages, /photosPicker\(/u);
  assert.match(store, /case "desktopLyricsBackgroundImage"/u);
  assert.match(pages, /case "slider"/u);
  assert.match(store, /case "settingNumber": updateSettingNumber/u);
  assert.doesNotMatch(player, /@Published var lyricTexts:/u);
  assert.doesNotMatch(player, /model\.repeatOne/u);
  assert.doesNotMatch(themedTab, /EchoNativeArtworkBackdrop\(/u);
  assert.match(themedTab, /appBackground/u);
  assert.match(appBackground, /activePage == "control" \|\| playerModel\.appearanceBackground == "artwork"/u);
  assert.ok(appBackground.indexOf('echoThemeBackground') > appBackground.indexOf('EchoNativeArtworkBackdrop'));
  assert.match(appBackground, /activePage != "control"[\s\S]*appearanceBackground == "custom"[\s\S]*appearanceImageUrl\.isEmpty/u);
  assert.match(player, /ZStack \{\s+echoWarmBackground\s+if !stableUrl\.isEmpty/u);
  assert.match(player, /@Binding var stableIdentity: String/u);
  assert.match(player, /stableIdentity: \$stableArtworkIdentity/u);
  assert.match(appBackground, /EchoNativeSakuraBackdrop/u);
  assert.match(player, /private struct EchoNativeSakuraBackdrop/u);
  assert.doesNotMatch(player, /EchoNativeThemePattern/u);
  assert.doesNotMatch(lyricsScroller, /scrollClipDisabled/u);
  assert.match(lyricsScroller, /let timeMs = line\.milliseconds/u);
  assert.match(lyricsScroller, /Text\(line\.text\)[\s\S]*\.shadow\(color: active/u);
  assert.match(lyricsScroller, /if timeMs >= 0 \{/u);
  assert.doesNotMatch(lyricsScroller, /timeMs >= 0 && !active/u);
  assert.match(pages, /pendingLibraryPageScroll = true/u);
  assert.match(pages, /libraryMode == "playlists" && library\.streaming\.selectedPlaylistId\.isEmpty/u);
  assert.match(pages, /DispatchQueue\.main\.async \{ scrollToLibraryIndex\(target, proxy: proxy\) \}/u);
  assert.equal((pages.match(/proxy\.scrollTo\(scrollTopId, anchor: \.top\)/gu) ?? []).length, 3);
  assert.match(pages, /private var librarySortMenu: some View/u);
  assert.match(pages, /@AppStorage\("echo\.library\.trackSort"\) private var libraryTrackSort = "default"/u);
  assert.match(pages, /"Default order" : "默认排序"[\s\S]*\.tag\("default"\)/u);
  assert.match(pages, /let sortingCollections = model\.payload\?\.library\?\.collections\.isEmpty == false/u);
  assert.match(pages, /Text\(library\.labels\.collections\)[\s\S]*librarySortMenu[\s\S]*EchoNativeDisplayModeButton/u);
  assert.match(pages, /let indexTitle: String/u);
  assert.match(payload, /let desktopLyricsSection = section\("desktopLyrics"/u);
  assert.match(payload, /picker\("desktopLyricsAnimation"/u);
  assert.match(store, /case "desktopLyricsEnabled"/u);
  assert.match(store, /case "desktopLyricsRainbowGradient"/u);
  assert.ok(pages.includes('Text("DISC \\(discNo)")'));
  assert.match(pages, /"action": "playlistPlay"/u);
  assert.match(pages, /"action": "streamingPlaylistOpen", "id": playlist\.id, "play": true/u);
  assert.match(libraryPlaylistCard, /Menu \{[\s\S]*"action": "playlistPlay"/u);
  assert.doesNotMatch(libraryPlaylistCard, /Image\(systemName: "play\.fill"\)/u);
  assert.match(streamingPlaylistMenu, /Menu \{[\s\S]*"play": true/u);
  assert.doesNotMatch(streamingPlaylistMenu, /Image\(systemName: "play\.fill"\)/u);
  assert.match(playlistDetail, /Menu \{[\s\S]*"action": "playlistPlay"/u);
  assert.doesNotMatch(playlistDetail, /Image\(systemName: "play\.fill"\)/u);
  assert.match(pages, /let trackCount: Int/u);
  assert.match(store, /let playWhenLoaded = payload\["play"\] as\? Bool \?\? false/u);
  assert.match(store, /if playWhenLoaded, let first = tracks\.first[\s\S]*play\(first, forcedMode: \.streaming\)/u);
  assert.equal((pages.match(/\.firstIndex\(of:/gu) ?? []).length, 6);
  assert.match(pages, /\.offset\(x: 11\)/u);
  assert.match(pages, /libraryTrackMenu\(track, labels: labels\)/u);
  assert.doesNotMatch(pages, /contentAnimationKey/u);
  assert.doesNotMatch(pages, /\.searchable\(text: libraryQueryBinding/u);
  assert.match(remoteClients, /secureMediaUrl\(value\.avatarUrl\)/u);
  assert.match(remoteClients, /host == "music\.126\.net" \|\| host\.hasSuffix\("\.music\.126\.net"\)/u);
  assert.match(remoteClients, /path: "\/api\/song\/enhance\/player\/url"/u);
  assert.match(remoteClients, /func trackDetail\(trackId: String\)/u);
  assert.match(remoteClients, /func dailyRecommendations\(\)/u);
  assert.match(store, /refreshDailyRecommendations\(force: false\)/u);
  assert.match(payload, /"recommendedTracks": persistent\.streamingRecommendedTracks/u);
  assert.match(pages, /"action": "streamingRecommendationsRefresh"/u);
  assert.match(payload, /let appearanceSection = section\("appearance"/u);
  assert.match(payload, /let motionSection = section\("motion"/u);
  assert.match(coreTypes, /var appearanceBackground = "theme"/u);
  assert.match(coreTypes, /desktopLyricsWidthScale = max\(0\.2, min\(1\.0, decodedWidthScale \?\? 1\.0\)\)/u);
  assert.doesNotMatch(coreTypes, /appearancePattern|backgroundMotionEnabled|artworkMotionEnabled/u);
  assert.doesNotMatch(payload, /appearancePattern|backgroundMotion|toggle\("artworkMotion"/u);
  assert.match(pages, /ColorPicker\(/u);
  assert.match(pages, /"action": "settingResetSection"/u);
  assert.match(store, /private func resetSettingsSection/u);
  assert.match(store, /case "playback":[\s\S]*playerModel\.eqEnabled = false/u);
  assert.match(store, /case "audioTags":[\s\S]*playerModel\.tags = tags\(for: currentTrack\)/u);
  assert.doesNotMatch(pages, /row\.resettable/u);
  assert.match(desktopLyrics, /currentLyric\.isEmpty[\s\S]*暂无歌曲数据/u);
  assert.match(desktopLyrics, /let bars: \[CGFloat\]/u);
  assert.ok(moreControls.indexOf('trackFavoriteCurrent') < moreControls.indexOf('Divider()'));
  assert.ok(moreControls.indexOf('desktopLyricsEnabled') < moreControls.indexOf('externalMetadataRefresh'));
  assert.ok(moreControls.indexOf('externalMetadataRefresh') < moreControls.indexOf('showSignalPath = true'));
  assert.ok(moreControls.indexOf('showSignalPath = true') < moreControls.indexOf('showEqualizer = true'));
  assert.match(payload, /"label": nowPlayingLabel/u);
  assert.match(widget, /supportedFamilies\(\[\.systemSmall, \.systemMedium\]\)/u);
  assert.match(widgetPlugin, /addTarget\(targetName, 'app_extension'/u);
  assert.match(widgetPlugin, /'PBXSourcesBuildPhase', 'Sources', target\.uuid/u);
  assert.match(player, /EchoNativeSplashView\(/u);
  assert.match(player, /Task\.sleep\(nanoseconds: 2_000_000_000\)/u);
  assert.match(splash, /EchoSplashSakuraField\(count: 100/u);
  assert.match(splash, /for petal in 0\.\.<5/u);
  assert.match(splash, /Text\("ECHO"\)/u);
  assert.match(splash, /Text\("ささやき"\)/u);
  assert.match(splash, /Text\("正在启动"\)/u);
  assert.match(remoteClients, /path: direct \? "\/api\/song\/lyric" : "\/lyric"/u);
  assert.match(remoteClients, /let tlyric: Lyrics\?/u);
  assert.match(remoteClients, /func albumTracks\(albumId: String\)[\s\S]*library\/albums\/\\\(encodedPathComponent\(albumId\)\)\/tracks/u);
  assert.match(store, /echoClient\.albumTracks\(albumId: albumId\)/u);
  assert.match(store, /loadedAlbumTracks[\s\S]*refreshedTracks \+ loadedAlbumTracks\.filter/u);
  assert.match(remoteClients, /response\.more == true/u);
  assert.match(remoteClients, /code != 200, !\[800, 801, 802, 803\]\.contains\(code\)/u);
  assert.match(neteaseLogin, /configuration\.websiteDataStore = \.nonPersistent\(\)/u);
  assert.match(localLibrary, /guard \(try\? AVAudioFile\(forReading: destination\)\) != nil/u);
});
